/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Appheader: typeof import('./src/components/Appheader.vue')['default']
    LoginForm: typeof import('./src/components/loginForm.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
